name: lorthew
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_nav_bar: ^5.0.6
  line_icons: ^2.0.3
  dropdown_button2: ^2.3.8
  flutter_animated_button: ^2.0.3
  animations: ^2.0.8
  flutter_animate: ^4.2.0+1
  intl: ^0.18.1
  printing: ^5.11.0
  flutter_form_builder: ^9.1.1
  psgc_picker: ^1.0.2
  pdf: ^3.10.6
  firebase_core: ^2.23.0
  firebase_auth: ^4.14.1
  cloud_firestore: ^4.13.2
  provider: ^6.1.1
  firebase_ui_auth: ^1.10.0
  flutter_spinkit: ^5.2.0
  google_fonts: ^6.1.0
  table_calendar: ^3.0.3
  email_auth: ^1.1.1
  flutterflow_widgets: ^0.0.7
  auto_size_text: 3.0.0
  cached_network_image: 3.2.1
  flutter_cache_manager: 3.3.1
  flutter_rating_bar: 4.0.1
  font_awesome_flutter: 10.6.0
  from_css_color: 2.0.0
  go_router: 7.1.1
  json_path: 0.6.2
  page_transition: 2.1.0
  path_provider: 2.0.14
  path_provider_android: 2.0.25
  path_provider_foundation: 2.2.2
  path_provider_platform_interface: 2.0.6
  shared_preferences: 2.2.2
  shared_preferences_android: 2.2.1
  shared_preferences_foundation: 2.3.4
  shared_preferences_platform_interface: 2.3.1
  shared_preferences_web: 2.2.1
  sqflite: 2.2.6
  timeago: 3.2.2
  url_launcher: 6.1.10
  url_launcher_android: 6.0.27
  url_launcher_ios: 6.1.4
  url_launcher_platform_interface: 2.1.2
  image_picker: ^1.0.4
  firebase_storage: ^11.5.3
  carousel_slider: ^4.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/images/
    - assets/images/Lorthew_Logo.png
  
  fonts:
    - family: Bebas
      fonts:
        - asset: assets/fonts/BebasNeue-Regular.ttf
          weight: 400

  uses-material-design: true
