// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4K43y6pKsYYALrllyrC4B4Issr45ZMZ4',
    appId: '1:1046479576619:web:8d93ed317f18046cf1946e',
    messagingSenderId: '1046479576619',
    projectId: 'lorthew-43da7',
    authDomain: 'lorthew-43da7.firebaseapp.com',
    storageBucket: 'lorthew-43da7.appspot.com',
    measurementId: 'G-ZXFDFND9EN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYREX8euLnrUAfJOdTBAqPfydnm3m_Fpc',
    appId: '1:1046479576619:android:f54a85b5bd4d1dd5f1946e',
    messagingSenderId: '1046479576619',
    projectId: 'lorthew-43da7',
    storageBucket: 'lorthew-43da7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDU1XbOfqmEkaqSEIniD8gLWy_60ZAPsbU',
    appId: '1:1046479576619:ios:476be58de48b80f1f1946e',
    messagingSenderId: '1046479576619',
    projectId: 'lorthew-43da7',
    storageBucket: 'lorthew-43da7.appspot.com',
    iosBundleId: 'com.example.lorthew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDU1XbOfqmEkaqSEIniD8gLWy_60ZAPsbU',
    appId: '1:1046479576619:ios:639b17c165210dcbf1946e',
    messagingSenderId: '1046479576619',
    projectId: 'lorthew-43da7',
    storageBucket: 'lorthew-43da7.appspot.com',
    iosBundleId: 'com.example.lorthew.RunnerTests',
  );
}
